//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eus.UI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public long RatingID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> AnswerID { get; set; }
        public Nullable<int> Rating1 { get; set; }
    }
}
