//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eus.UI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic
    {
        public int TopicID { get; set; }
        public string Topic1 { get; set; }
        public string Description { get; set; }
        public string TopicTitleURL { get; set; }
        public string Search { get; set; }
        public string Tags { get; set; }
        public Nullable<int> AnswerCount { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    }
}
